# Generated by Django 5.1.4 on 2024-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputset',
            name='garment_thumbnail_url',
            field=models.CharField(blank=True, help_text='S3 URL for garment thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='model_thumbnail_url',
            field=models.CharField(blank=True, help_text='S3 URL for model thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tryon',
            name='thumbnail_url',
            field=models.CharField(blank=True, help_text='S3 URL for tryon thumbnail', max_length=500, null=True),
        ),
    ]
