# Generated by Django 5.1.4 on 2024-12-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inputset_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputset',
            name='garment_image',
        ),
        migrations.RemoveField(
            model_name='inputset',
            name='garment_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='inputset',
            name='model_image',
        ),
        migrations.RemoveField(
            model_name='inputset',
            name='model_thumbnail_url',
        ),
        migrations.AddField(
            model_name='inputset',
            name='garment_image_old',
            field=models.CharField(blank=True, help_text='Old S3 URL for garment image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='garment_key',
            field=models.CharField(blank=True, help_text='S3 key for garment image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='garment_thumb_key',
            field=models.CharField(blank=True, help_text='S3 key for garment thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='garment_thumbnail_url_old',
            field=models.CharField(blank=True, help_text='Old S3 URL for garment thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='model_image_old',
            field=models.CharField(blank=True, help_text='Old S3 URL for model image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='model_key',
            field=models.CharField(blank=True, help_text='S3 key for model image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='model_thumb_key',
            field=models.CharField(blank=True, help_text='S3 key for model thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inputset',
            name='model_thumbnail_url_old',
            field=models.CharField(blank=True, help_text='Old S3 URL for model thumbnail', max_length=500, null=True),
        ),
    ]
