# Generated by Django 5.1.4 on 2024-12-26 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_model_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelversion',
            options={'ordering': ['-elo_rating', '-created_at']},
        ),
        migrations.AddField(
            model_name='modelversion',
            name='elo_rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.CreateModel(
            name='RankedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loser_tryon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_rankings', to='main.tryon')),
                ('tryon_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='main.tryonbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
                ('winner_tryon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_rankings', to='main.tryon')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'winner_tryon', 'loser_tryon')},
            },
        ),
    ]
