# Generated by Django 5.1.4 on 2024-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_modelversion_options_modelversion_elo_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedpair',
            name='loser_rating_after',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rankedpair',
            name='loser_rating_before',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rankedpair',
            name='winner_rating_after',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rankedpair',
            name='winner_rating_before',
            field=models.IntegerField(null=True),
        ),
    ]
