# Generated by Django 5.1.4 on 2024-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rankedpair_loser_rating_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='is_api_implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='tray_code',
            field=models.CharField(blank=True, help_text='Code used in tryon-tray package', max_length=50),
        ),
    ]
