# Generated by Django 5.1.4 on 2024-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_modelversion_is_api_implemented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryon',
            name='is_generated_by_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tryon',
            name='resolution',
            field=models.CharField(blank=True, help_text='Image resolution in format WIDTHxHEIGHT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tryon',
            name='time_taken',
            field=models.FloatField(blank=True, help_text='Time taken in seconds for API generation', null=True),
        ),
        migrations.AlterField(
            model_name='tryon',
            name='notes',
            field=models.JSONField(default=dict, help_text='Store notes as JSON'),
        ),
    ]
