# Generated by Django 5.1.4 on 2024-12-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tryon_is_generated_by_api_tryon_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryon',
            name='notes',
            field=models.CharField(help_text='Store notes as Text', max_length=500),
        ),
    ]
