# Generated by Django 5.1.4 on 2024-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tryon_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='price_per_inference',
            field=models.FloatField(default=0.04, help_text='Cost in USD per API call'),
        ),
        migrations.AddField(
            model_name='tryon',
            name='price_per_inference',
            field=models.FloatField(blank=True, help_text='Cost in USD for this inference', null=True),
        ),
    ]
