# Generated by Django 5.1.4 on 2024-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_modelversion_price_per_inference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
