# Generated by Django 5.2 on 2025-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pagelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonbatch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
